kind: Service
apiVersion: v1
metadata:
  name: front-end
spec:
  selector:
    app: frontendpasantias
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
  template:
    metadata:
      labels:
        app: ${CIRCLE_PROJECT_REPONAME}
    spec:
      containers:
      - name: frontendpasantias
        image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP