apiVersion: v1
kind: Service
metadata:
  name: pasantias-frontend
  labels:
    app: pasantiaseam
spec:
  ports:
    - port: 3000
  selector:
    app: pasantias-frontend
    tier: frontend
  type: LoadBalancer